apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-graalvm-testing
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 1
  workshops:
  - name: lab-graalvm-testing
    reserved: 0
    expires: 60m
    orphaned: 15m
