apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-graalvm-testing
spec:
  title: GraalVM Testing
  description: A sample workshop using Markdown
  url: https://github.com/eduk8s-labs/lab-graalvm-testing
  content:
    image: ghcr.io/eduk8s-labs/eduk8s-labs/graalvm-environment@sha256:855bfc76adee12ed29f3c250ce13ef6b666599f57d8f3e6f8d4084337333624f
    #files: github.com/eduk8s-labs/lab-graalvm-testing
    files: imgpkg+https://ghcr.io/eduk8s-labs/eduk8s-labs/lab-graalvm-testing:latest
  session:
    namespaces:
      budget: medium
    resources:
      memory: 4Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
