apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-graalvm-testing
spec:
  title: GraalVM Testing
  description: A sample workshop using Markdown
  url: https://github.com/eduk8s-labs/lab-graalvm-testing
  content:
    image: ghcr.io/eduk8s-labs/eduk8s-labs/graalvm-environment:c11ea94c227238b2d9f5f97463983478819246f7
    files: github.com/eduk8s-labs/lab-graalvm-testing
  session:
    namespaces:
      budget: medium
    resources:
      memory: 4Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
